### ISSUE TITLE
Nothing

### ISSUE THREAD

**Issue by scoooooott** [jiguan/springboot-jms-realtime-messaging#2]
Nothing

**Comment by SoapCanFly** [comment]
``public static void main(String[] args) throws Exception {
        SpringApplication.run(GunsApplication.class, args);
        //begin---------here
        BrokerService broker = new BrokerService();
        // configure the broker
        broker.addConnector("vm://localhost");
        broker.setUseJmx(false);
        broker.setPersistent(false);
        broker.start();
        //end-----------here
        logger.info("GunsApplication is sussess!");
    }``
